# Generated by Django 6.0.6 on 2026-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Designation', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('Date_Joined', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
    ]
